name: car_connect
description: A new Flutter project.
version: 0.0.1+1
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #General
  injectable: 2.3.0
  get_it: 7.6.2
  auto_route: 7.8.3
  freezed: 2.4.1
  flutter_bloc: 8.1.3
  provider: 6.0.5
  intl: 0.18.1
  flutter_osm_plugin: 0.60.5

  #Https
  dio: 5.3.2
  retrofit: 4.0.1
  internet_connection_checker: 1.0.0+1
  json_serializable: 6.7.1
  pretty_dio_logger: 1.3.1

  #DB
  hive: 2.2.3
  hive_flutter: 1.1.0

  #UI
  cupertino_icons: 1.0.2
  flutter_screenutil: 5.9.0
  flex_color_scheme: 7.3.1
  flutter_svg: 2.0.7
  flutter_colorpicker: 1.0.3

  #Utils
  flutter_device_type: 0.4.0
  flutter_hooks: 0.18.6
  hooked_bloc: 1.4.2
  fimber_io: 0.7.0
  hexcolor: 3.0.1
  collection: 1.18.0
  equatable: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  mockito: 5.4.2
  bloc_test: 9.1.4
  build_runner: 2.4.6
  injectable_generator: 2.4.0
  auto_route_generator: 7.3.1
  freezed_annotation: 2.4.1
  flutter_gen_runner: 5.3.2
  hive_generator: 2.0.1
  json_annotation: 4.8.1
  retrofit_generator: 7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: pl

flutter_gen:
  output: lib/generated/assets/
  integrations:
    flutter_svg: true
